data_path: "data/train" # not used in template repo
val_path: "data/val" # not used in template repo

# default exp values
exp:
  policy: "PPO"
  env_gen_fn: "get_random_graph_env"
  env_gen_fn_nm: "truerand"

  policy_params:
    verbose: 1

  trainer_params:
    total_timesteps: 1e7
    log_interval: 1000
    save_interval: 50000

  env_gen_fn_params:
    num_nodes: 6
    min_dist: 0
    max_dist: 100
